### **BASIC DATA CLEANING**

In [1]:
## IMPORT LIBRARIES
import pandas as pd 
import numpy as np

## LOAD THE DATASET
df = pd.read_csv('IRIS_Dataset.csv')  

# Copy the DataFrame to avoid modifying the original dataset
data = df.copy()
data

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

#####  ✅ Remove Duplicates Records -- Delete duplicate rows.

In [2]:
data.duplicated() # Check for duplicate rows

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [3]:
# Before removing duplicates, let's check how many duplicate rows are present in the dataset
data.duplicated().sum() # Count the number of duplicate rows

np.int64(3)

In [4]:
new_data = data.drop_duplicates() # Remove duplicate rows and return a new DataFrame without duplicates

In [5]:
# After removing duplicates, let's check how many duplicate rows are present in the new dataset
new_data.duplicated().sum()

np.int64(0)

##### ✅ Remove Irrelevant Columns -- Delete columns that are not useful for analysis.

In [6]:
##  THERE IS NO SUCH IRRELEVANT DATA COLUMN IN THE NEW DATASET. SO, NO NEED TO REMOVE ANYTHING. ##

##### ✅ Fixing Inconsistent Formats -- Standardize the format of data in columns.

In [7]:
# Changing the values of the 'Species' column to more readable format

# data.loc[['row_condition'], ['column_name']] = new_value , 
# .loc is used to access a group of rows and columns by labels or a boolean array.
mask1 = new_data["species"].eq("Iris-setosa") # Create a boolean mask for rows where 'Species' is 'Iris-setosa'
new_data.loc[mask1, "species"] = "Setosa"
mask2 = new_data["species"].eq("Iris-versicolor") # Create a boolean mask for rows where 'Species' is 'Iris-versicolor'
new_data.loc[mask2, "species"] = "Versicolor"
mask3 = new_data["species"].eq("Iris-virginica") # Create a boolean mask for rows where 'Species' is 'Iris-virginica'
new_data.loc[mask3, "species"] = "Virginica"

new_data  # Display the cleaned dataset with updated 'Species' values

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[147 rows x 5 columns]

##### ✅ Fixing Impossible values -- Correct or Replace the impossible values with NaN.
###### **NOTE** :  NaN will further be handled in the Data Preprocessing step

In [8]:
# Any type of length can't be negative. So, we will replace any negative values in the dataset with NaN (Not a Number).

new_data.loc[new_data['sepal_length'] < 0, 'sepal_length'] = np.nan  # Replace negative values in 'sepal_length' with NaN
new_data.loc[new_data['sepal_width'] < 0, 'sepal_width'] = np.nan  # Replace negative values in 'sepal_width' with NaN
new_data.loc[new_data['petal_length'] < 0, 'petal_length'] = np.nan  # Replace negative values in 'petal_length' with NaN
new_data.loc[new_data['petal_width'] < 0, 'petal_width'] = np.nan  # Replace negative values in 'petal_width' with NaN

new_data # Display the dataset after replacing negative values with NaN

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[147 rows x 5 columns]

 ##### ✅ Remove Missing values -- Remove or Replace the impossible values with NaN.

In [9]:
# Check for toatl number of missing values present in each cloumn in the dataset.
new_data.isnull().sum() # Count the number of missing values in each column

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [10]:
## THERE IS NO SUCH MISSING VALUE IN THE DATASET. SO, NO NEED TO HANDLE MISSING VALUES. ##

##### ✅ Fixing Missing & Invalid Target values -- Delete the entire row if the target value is missing or invalid.

In [11]:
## THERE IS NO INVALID AND MISSING TARGET VALUE IN THE NEW DATASET. SO, NO NEED TO HANDLE INVALID AND MISSING TARGET VALUES. ##

In [12]:
## FINAL CLEANED DATASET ##
new_data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[147 rows x 5 columns]